apiVersion: v1
kind: Service
metadata:
  name: tic-tac-toe-client-service
spec:
  selector:
    app: tic-tac-toe-client
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 80

  type: NodePort  # Use NodePort if testing locally
