apiVersion: v1
kind: Service
metadata:
  name: tic-tac-toe-server-service
spec:
  selector:
    app: tic-tac-toe-server
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000

  type: NodePort  